# Generated by Django 4.2.6 on 2023-10-26 21:14

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "setor",
                    models.CharField(
                        choices=[("varejo", "varejo"), ("transporte", "transporte")],
                        max_length=100,
                    ),
                ),
                ("logo", models.ImageField(upload_to="logo_empresas")),
                ("descricao", models.TextField(max_length=2000)),
                (
                    "uf",
                    models.CharField(
                        choices=[("rj", "rj"), ("sp", "sp")], max_length=2
                    ),
                ),
                (
                    "data_de_criacao",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "data_de_modificacao",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023,
                            10,
                            26,
                            21,
                            14,
                            15,
                            532980,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Filme",
        ),
    ]
