# Generated by Django 4.2.6 on 2023-11-21 20:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("empresa", "0003_alter_empresa_data_de_modificacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="data_de_modificacao",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 21, 20, 22, 35, 952280, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "servico",
                    models.CharField(
                        choices=[
                            ("dupla materialdade", "dupla materialdade"),
                            ("perception esg", "perception esg"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "responsavel",
                    models.CharField(
                        choices=[
                            ("gustavo baraldi", "gustavo baraldi"),
                            ("estevam pereira", "estevam pereira"),
                        ],
                        max_length=100,
                    ),
                ),
                ("data_de_deadline", models.DateField()),
                ("data_de_aprovacao", models.DateField()),
                ("data_de_envio", models.DateField()),
                ("data_de_pedido", models.DateField()),
                ("valor", models.FloatField()),
                (
                    "linha_de_servico",
                    models.CharField(
                        choices=[
                            ("reportes", "reportes"),
                            ("jornada climatica", "jornada climatica"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "estagio",
                    models.CharField(
                        choices=[("aprovado", "aprovado"), ("pendente", "pendente")],
                        max_length=100,
                    ),
                ),
                (
                    "id_empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projetos",
                        to="empresa.empresa",
                    ),
                ),
            ],
        ),
    ]
