# Generated by Django 4.2.6 on 2023-11-21 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresa", "0005_alter_empresa_data_de_modificacao_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projeto",
            old_name="id_empresa",
            new_name="empresa",
        ),
        migrations.AlterField(
            model_name="empresa",
            name="data_de_modificacao",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 21, 20, 32, 14, 671007, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
