# Generated by Django 4.2.6 on 2023-11-22 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresa", "0006_rename_id_empresa_projeto_empresa_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projeto",
            name="linha_de_servico",
        ),
        migrations.AlterField(
            model_name="empresa",
            name="data_de_modificacao",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 22, 20, 23, 39, 498246, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
