# Generated by Django 4.2.6 on 2023-11-22 20:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("empresa", "0007_remove_projeto_linha_de_servico_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projeto",
            name="servico",
        ),
        migrations.AlterField(
            model_name="empresa",
            name="data_de_modificacao",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 22, 20, 48, 32, 845835, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        choices=[
                            ("dupla materialdade", "dupla materialdade"),
                            ("perception esg", "perception esg"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servico",
                        to="empresa.projeto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Linha_de_servico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        choices=[
                            ("reportes", "reportes"),
                            ("jornada climatica", "jornada climatica"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linha_de_servico",
                        to="empresa.projeto",
                    ),
                ),
            ],
        ),
    ]
