# Generated by Django 4.2.6 on 2023-11-23 14:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("empresa", "0009_alter_empresa_data_de_modificacao_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proposta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "responsavel",
                    models.CharField(
                        choices=[
                            ("gustavo baraldi", "gustavo baraldi"),
                            ("estevam pereira", "estevam pereira"),
                        ],
                        max_length=100,
                    ),
                ),
                ("data_de_deadline", models.DateField()),
                ("data_de_aprovacao", models.DateField()),
                ("data_de_envio", models.DateField()),
                (
                    "data_de_pedido",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("valor", models.FloatField()),
                (
                    "estagio",
                    models.CharField(
                        choices=[("aprovado", "aprovado"), ("pendente", "pendente")],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="projeto",
            name="empresa",
        ),
        migrations.RemoveField(
            model_name="servico",
            name="projeto",
        ),
        migrations.AlterField(
            model_name="empresa",
            name="data_de_modificacao",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 23, 14, 15, 10, 158474, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.DeleteModel(
            name="Linha_de_servico",
        ),
        migrations.DeleteModel(
            name="Projeto",
        ),
        migrations.AddField(
            model_name="proposta",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="propostas",
                to="empresa.empresa",
            ),
        ),
        migrations.AddField(
            model_name="servico",
            name="proposta",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="servicos",
                to="empresa.proposta",
            ),
        ),
    ]
