# Generated by Django 4.2.6 on 2023-11-30 18:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0018_alter_empresa_data_de_modificacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='cidade',
        ),
        migrations.AddField(
            model_name='contato',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contato', to='empresa.endereco'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='data_de_modificacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 30, 18, 49, 49, 184315, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='data_de_aprovacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 30, 18, 49, 49, 184315, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='data_de_envio',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 30, 18, 49, 49, 184315, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 30, 18, 49, 49, 184315, tzinfo=datetime.timezone.utc)),
        ),
    ]
