# Generated by Django 4.2.6 on 2023-12-02 15:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0021_remove_empresa_uf_empresa_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='data_de_modificacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 15, 55, 15, 969721, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='data_de_aprovacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 15, 55, 15, 969721, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='data_de_envio',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 15, 55, 15, 969721, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 15, 55, 15, 969721, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_inicio', models.DateTimeField(auto_now_add=True)),
                ('proposta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='projeto', to='empresa.proposta')),
            ],
        ),
    ]
