# Generated by Django 4.2.6 on 2023-12-02 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0022_alter_empresa_data_de_modificacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='data_de_inicio',
            new_name='data_de_cadastro',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='data_de_modificacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 16, 11, 56, 427260, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='data_de_aprovacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 16, 11, 56, 427260, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='data_de_envio',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 16, 11, 56, 427260, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 16, 11, 56, 427260, tzinfo=datetime.timezone.utc)),
        ),
    ]
