# Generated by Django 4.2.6 on 2023-12-04 16:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0023_rename_data_de_inicio_projeto_data_de_cadastro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='empresa',
            name='data_de_modificacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 4, 16, 19, 23, 337691, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='data_de_aprovacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 4, 16, 19, 23, 337691, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='data_de_envio',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 4, 16, 19, 23, 337691, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 4, 16, 19, 23, 337691, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='projeto',
            name='status_projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projeto', to='empresa.statusprojeto'),
        ),
    ]
